SELECT A.PRODUTO, 
	   MAX(C.IMPORTACAO_CADERNO_PRECO_ITEM_WS),
	   C.REGISTRO_ANVISA,
	   A.REGISTRO_MS AS REGISTRO_INTERNO, 
	   B.EAN, C.EAN AS EAN_ANVISA
FROM PRODUTOS_FARMACIA A
JOIN PRODUTOS_EAN B ON A.PRODUTO = B.PRODUTO
JOIN IMPORTACOES_CADERNOS_PRECOS_ITENS_WS C ON B.EAN = C.EAN
	WHERE C.REGISTRO_ANVISA <> A.REGISTRO_MS 
		  AND A.VENDA_CONTROLADA = 's'
		  AND C.REGISTRO_ANVISA <> '0000000000000'
		  AND LEN(C.REGISTRO_ANVISA) = 13
		  AND C.REGISTRO_ANVISA NOT LIKE '%[^0-9]%'
		  AND C.REGISTRO_ANVISA <> C.EAN
	GROUP BY  A.PRODUTO, B.EAN,  A.REGISTRO_MS, C.EAN, C.REGISTRO_ANVISA



UPDATE PRODUTOS_FARMACIA SET REGISTRO_MS = C.REGISTRO_ANVISA
	FROM PRODUTOS_FARMACIA A
	JOIN PRODUTOS_EAN B ON A.PRODUTO = B.PRODUTO
	JOIN IMPORTACOES_CADERNOS_PRECOS_ITENS_WS C ON B.EAN = C.EAN
		WHERE C.REGISTRO_ANVISA <> A.REGISTRO_MS 
		       AND A.VENDA_CONTROLADA = 's'
		       AND C.REGISTRO_ANVISA <> '0000000000000'
		       AND LEN(C.REGISTRO_ANVISA) = 13
		       AND C.REGISTRO_ANVISA NOT LIKE '%[^0-9]%'
		       AND C.REGISTRO_ANVISA <> C.EAN




SELECT A.PRODUTO, 
	   MAX(C.IMPORTACAO_CADERNO_PRECO_ITEM_WS) AS MAXI,
	   C.REGISTRO_ANVISA,
	   A.REGISTRO_MS AS REGISTRO_INTERNO, 
	   B.EAN, C.EAN AS EAN_ANVISA
--INTO #TESTE
FROM PRODUTOS_FARMACIA A
JOIN PRODUTOS_EAN B ON A.PRODUTO = B.PRODUTO
JOIN IMPORTACOES_CADERNOS_PRECOS_ITENS_WS C ON B.EAN = C.EAN
	WHERE C.REGISTRO_ANVISA <> A.REGISTRO_MS 
		  AND A.VENDA_CONTROLADA = 's'
		  AND C.REGISTRO_ANVISA <> '0000000000000'
		  AND LEN(C.REGISTRO_ANVISA) = 13
		  AND C.REGISTRO_ANVISA NOT LIKE '%[^0-9]%'
		  AND C.REGISTRO_ANVISA <> C.EAN
		  AND A.PRODUTO = 9341
		  CASE WHEN COUNT(A.PRODUTO) > 1 THEN AND C.REGISTRO_ANVISA = '1181904540209'
	GROUP BY  A.PRODUTO, B.EAN,  A.REGISTRO_MS, C.EAN, C.REGISTRO_ANVISA
